In [1]:
# ==========================================================
# TASK 3
# Vectorized Convolutional Forward Pass using im2col
# ==========================================================

# ----------------------------------------------------------
# Step 1 - Import Libraries
# ----------------------------------------------------------

import numpy as np
from scipy import signal

print("Libraries Imported Successfully")


# ----------------------------------------------------------
# Step 2 - Create Input Image
# ----------------------------------------------------------

np.random.seed(42)

# Input image
# Format: Height x Width x Channels

image = np.random.randn(6, 6, 3)

print("Input Image Shape:", image.shape)


# ----------------------------------------------------------
# Step 3 - Create Convolution Filters
# ----------------------------------------------------------

# Number of output filters
num_filters = 2

# Filter size
filter_size = 3

# Create filters
filters = np.random.randn(
    filter_size,
    filter_size,
    3,
    num_filters
) * 0.1

# Bias
bias = np.zeros(num_filters)

print("Filter Shape:", filters.shape)


# ----------------------------------------------------------
# Step 4 - im2col Function
# ----------------------------------------------------------

def im2col(image, filter_size, stride=1, padding=0):

    # Add padding around image
    padded_image = np.pad(
        image,
        (
            (padding, padding),
            (padding, padding),
            (0, 0)
        ),
        mode="constant"
    )

    height = padded_image.shape[0]
    width = padded_image.shape[1]
    channels = padded_image.shape[2]

    output_height = (
        height - filter_size
    ) // stride + 1

    output_width = (
        width - filter_size
    ) // stride + 1

    columns = []

    # Extract image patches
    for row in range(
        0,
        output_height * stride,
        stride
    ):

        for col in range(
            0,
            output_width * stride,
            stride
        ):

            patch = padded_image[
                row:row + filter_size,
                col:col + filter_size,
                :
            ]

            columns.append(
                patch.reshape(-1)
            )

    return np.array(columns)


# ----------------------------------------------------------
# Step 5 - Convert Image into Columns
# ----------------------------------------------------------

stride = 1
padding = 1

columns = im2col(
    image,
    filter_size,
    stride,
    padding
)

print("im2col Shape:", columns.shape)


# ----------------------------------------------------------
# Step 6 - Reshape Filters
# ----------------------------------------------------------

filter_columns = filters.reshape(
    filter_size * filter_size * 3,
    num_filters
)

print(
    "Reshaped Filter Shape:",
    filter_columns.shape
)


# ----------------------------------------------------------
# Step 7 - Vectorized Convolution
# ----------------------------------------------------------

output = np.dot(
    columns,
    filter_columns
)

# Add bias
output = output + bias


# ----------------------------------------------------------
# Step 8 - Reshape Output
# ----------------------------------------------------------

output_height = (
    image.shape[0] + 2 * padding - filter_size
) // stride + 1

output_width = (
    image.shape[1] + 2 * padding - filter_size
) // stride + 1

output = output.reshape(
    output_height,
    output_width,
    num_filters
)


# ----------------------------------------------------------
# Step 9 - Display Result
# ----------------------------------------------------------

print("Output Shape:", output.shape)

print("\nConvolution Output:")

print(output)


# ----------------------------------------------------------
# Step 10 - Check Convolution
# ----------------------------------------------------------

print("\nConvolution Completed Successfully")

print(
    "Minimum Output:",
    round(output.min(), 4)
)

print(
    "Maximum Output:",
    round(output.max(), 4)
)

print(
    "Mean Output:",
    round(output.mean(), 4)
)

Libraries Imported Successfully
Input Image Shape: (6, 6, 3)
Filter Shape: (3, 3, 3, 2)
im2col Shape: (36, 27)
Reshaped Filter Shape: (27, 2)
Output Shape: (6, 6, 2)

Convolution Output:
[[[ 0.27037507 -0.52852268]
  [ 0.12145027  0.06936134]
  [-0.18338801 -0.05069939]
  [-0.17893546 -0.45359179]
  [-0.06905854 -0.26654376]
  [-0.01098504 -0.34529031]]

 [[ 0.49416303 -0.24801683]
  [ 0.61087314  0.20211392]
  [ 0.10666691 -0.2977554 ]
  [-0.01102286 -0.15649284]
  [-0.05693296  0.69597928]
  [ 0.9239493  -0.04260344]]

 [[ 0.11081359 -0.02756912]
  [ 0.19424955 -0.0868656 ]
  [-0.82443626 -0.36041846]
  [ 0.07929838 -0.89711399]
  [-0.48878835 -0.8725781 ]
  [-0.64243057 -0.54613568]]

 [[-0.33558785  0.61449846]
  [ 0.29639443 -1.13239029]
  [-0.55328825  0.68083269]
  [ 0.05290728  0.58480897]
  [-0.55038577  0.83682107]
  [ 0.45277662  0.12004903]]

 [[ 0.18654671  0.20394752]
  [ 0.02654629 -0.69760472]
  [ 0.3379853   0.10928072]
  [ 0.09678342 -0.04928618]
  [ 0.02477676  0.543